src = open("src/jarvix_memory/decision/jev_logits.py", encoding="utf-8").read()
n1 = src.count('["O", "N"]')
src = src.replace('["O", "N"]', '["OUI", "NON"]')
src = src.replace('p.get("O", 0.5)', 'p.get("OUI", 0.5)')
src = src.replace('s_raw.get("O", 0.5)', 's_raw.get("OUI", 0.5)')
src = src.replace('d_raw.get("O", 0.5)', 'd_raw.get("OUI", 0.5)')
src = src.replace("# first letters", "")
open("src/jarvix_memory/decision/jev_logits.py", "w", encoding="utf-8").write(src)
print("patched", n1, "noul sites")
